fixtures:
  repositories:
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.1'
    cron_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core.git'
      ref: '1.0.0'
      puppet_version: ">= 6.0.0"
    mount_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-mount_core.git'
      ref: '1.0.2'
      puppet_version: ">= 6.0.0"
  symlinks:
    resource: "#{source_dir}"
