name 'emahags-resource'
version '0.1.0'
source 'git://github.com/emahags/puppet-module-resource.git'
author 'emahags'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/emahags/puppet-module-resource'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
