name 'puppet-module-resource'
version '0.2.0'
source 'git://github.com/emahags/puppet-module-resource.git'
author 'emahags'
license 'Apache License, Version 2.0'
summary 'Manage puppet resources'
description 'Manage puppet resources'
project_page 'https://github.com/emahags/puppet-module-resource'

dependency 'puppetlabs/stdlib', '>= 4.5.1'
